build:
    maxIssues: 0

comments:
    active: false  # Disable documentation warnings (optional)

style:
    MagicNumber:
        active: false # It's annoying really
    UnusedPrivateMember:
        ignoreAnnotated: [ "Composable", "Preview" ]  # Ignore unused parameters in Compose previews
    WildcardImport:
        active: false  # Allow wildcard imports for Compose

formatting:
    MaximumLineLength:
        maxLineLength: 120  # Allow longer lines for better Compose readability

complexity:
    LongParameterList:
        ignoreAnnotated: [ "Composable" ]
        ignoreDefaultParameters: true
    LongMethod:
        ignoreAnnotated: [ "Composable" ]

naming:
    FunctionNaming:
        ignoreAnnotated: [ "Composable" ]
